# serverless.yml
service:
  name: StudentApp

provider:
  name: aws
  runtime: nodejs12.x
  stage: test
  region: eu-central-1
  role: arn:aws:iam::667505010803:role/service-role/lambda-role-8vrgj12i

functions:
  # Configure API
  login:
    handler: src/index.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /
      
